apiVersion: apps/v1
kind: Deployment
metadata:
    name: sale-deployment
    labels:
        app: sale-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sale-service
    template:
        metadata:
            labels:
                app: sale-service
        spec:
            containers:
                - name: sale-node
                  image: sale-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 7804
                  env:
                      - name: NODE_ENV
                        value: "production"
                      - name: SERVER_APP_PORT
                        value: "7804"
                      - name: DB_HOST
                        value: "mariadb-service"
                      - name: DB_PORT
                        value: "3306"
                      - name: DB_USER
                        value: "root"
                      - name: DB_PASSWORD
                        value: "root123456"
                      - name: DB_NAME
                        value: "sistema_supermercado_db"
                      - name: SERVER_REDIRECTION
                        value: "PROD"
