apiVersion: v1
kind: Service
metadata:
    name: sale-service
spec:
    type: ClusterIP
    selector:
        app: sale-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 7804
