apiVersion: v1
kind: Service
metadata:
    name: company-service
spec:
    type: ClusterIP
    selector:
        app: company-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 7806
